// MFD Configs based on work by Kimi and used with permission
// https://steamcommunity.com/sharedfiles/filedetails/?id=312724602

class MFD_Pilot_9
{
    topLeft="MFD_9_TL";
    topRight="MFD_9_TR";
    bottomLeft="MFD_9_BL";
    borderLeft=0;
    borderRight=0;
    borderTop=0;
    borderBottom=0;
    color[]={1,1,1,1};
    helmetMountedDisplay=0;
    helmetPosition[]={-0.037500001,0.037500001,0.1};
    helmetRight[]={0.075000003,0,0};
    helmetDown[]={0,-0.075000003,0};
    font="LucidaConsoleB";
    turret[]={-2};
    class Bones
    {
    };
    class Draw
    {
        alpha=1;
        color[]={0,0.12,0};
        condition="on";
        class CollectiveGroup
        {
            condition="simulRTD";
            class CollectiveText
            {
                type="text";
                source="static";
                text="%";
                align="right";
                scale=1;
                pos[]=
                {
                    {0.22,0.2},
                    1
                };
                right[]=
                {
                    {0.28,0.2},
                    1
                };
                down[]=
                {
                    {0.22,0.23999999},
                    1
                };
            };
            class CollectiveNumber
            {
                type="text";
                source="rtdCollective";
                sourceScale=100;
                align="left";
                scale=1;
                pos[]=
                {
                    {0.22,0.2},
                    1
                };
                right[]=
                {
                    {0.28,0.2},
                    1
                };
                down[]=
                {
                    {0.22,0.23999999},
                    1
                };
            };
        };
        class SpeedNumber
        {
            type="text";
            source="speed";
            sourceScale=3.5999999;
            align="left";
            scale=1;
            pos[]=
            {
                {0.28,0.45199999},
                1
            };
            right[]=
            {
                {0.31999999,0.45199999},
                1
            };
            down[]=
            {
                {0.28,0.49200001},
                1
            };
        };
        class AltNumber
        {
            type="text";
            source="altitudeAGL";
            sourceScale=1;
            sourceOffset=-2;
            align="left";
            scale=1;
            pos[]=
            {
                {0.75,0.45199999},
                1
            };
            right[]=
            {
                {0.79000002,0.45199999},
                1
            };
            down[]=
            {
                {0.75,0.49200001},
                1
            };
        };
        class CruiseMode
        {
            condition="1+((altitudeASL-27) min 1) - autohover";
            class AltNumberASL
            {
                type="text";
                source="altitudeASL";
                sourceScale=1;
                align="left";
                scale=1;
                pos[]=
                {
                    {0.81,0.16},
                    1
                };
                right[]=
                {
                    {0.85000002,0.16},
                    1
                };
                down[]=
                {
                    {0.81,0.2},
                    1
                };
            };
        };
    };
};
