#define AUTOHOVER_COLLECTIVE_RATE 0.005
#define AUTOHOVER_COLLECTIVE_MAX_CHANGE 0.05
#define AUTOHOVER_MAX_COLLECTIVE 1
#define AUTOHOVER_MIN_COLLECTIVE 0
#define AUTOHOVER_COLLECTIVE_UPDATE_DELAY 0.02
#define AUTOHOVER_VAR_NAME "CRM_AUTOHOVER_ON"
#define AUTOHOVER_CAPABLE_PROP CRM_AUTOHOVER_CAPABLE