#define AUTOPILOT_ENABLED_VAR_NAME "CRM_AUTOPILOT_ENABLED"
#define AUTOPILOT_COPILOT_VAR_NAME "CRM_AUTOPILOT_COPILOT"
#define AUTOPILOT_WP_VAR_NAME "CRM_AUTOPILOT_WP"
#define AUTOPILOT_HEADING_WP_DIST 100000